version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: Postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dockerweb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_paw
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}    
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS} 
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - dockerweb

volumes:
  pgdata:

networks:
  dockerweb:
    name: siec-paw-food-helper
    external: true